// Experience Section Logo's
import RealpageLogo from "./assets/company_logo/realpage.jpg";
import AspironLogo from "./assets/company_logo/Aspiron.jpeg";
import InflocurisLogo from "./assets/company_logo/Inflocuris.jpeg";

export const SkillsCloud = [
  {
    label: "React.js",
    x: 50,
    y: 40,
    size: 100,
    bg: "bg-blue-500/20",
    text: "text-blue-100",
    delay: 0,
  },
  {
    label: "JavaScript",
    x: 70,
    y: 28,
    size: 92,
    bg: "bg-yellow-500/20",
    text: "text-yellow-100",
    delay: 0.2,
  },
  {
    label: "TypeScript",
    x: 32,
    y: 20,
    size: 90,
    bg: "bg-emerald-500/20",
    text: "text-emerald-100",
    delay: 0.3,
  },
  {
    label: "Redux",
    x: 68,
    y: 55,
    size: 82,
    bg: "bg-purple-500/20",
    text: "text-purple-100",
    delay: 0.4,
  },
  {
    label: "Context API",
    x: 42,
    y: 60,
    size: 76,
    bg: "bg-indigo-500/20",
    text: "text-indigo-100",
    delay: 0.5,
  },
  {
    label: "Tailwind",
    x: 20,
    y: 45,
    size: 78,
    bg: "bg-cyan-500/20",
    text: "text-cyan-100",
    delay: 0.6,
  },
  {
    label: "HTML5",
    x: 18,
    y: 70,
    size: 72,
    bg: "bg-orange-500/20",
    text: "text-orange-100",
    delay: 0.3,
  },
  {
    label: "CSS3",
    x: 82,
    y: 65,
    size: 72,
    bg: "bg-sky-500/20",
    text: "text-sky-100",
    delay: 0.5,
  },
  {
    label: "React Native",
    x: 38,
    y: 75,
    size: 70,
    bg: "bg-blue-400/20",
    text: "text-blue-100",
    delay: 0.4,
  },
  {
    label: "Component Design",
    x: 55,
    y: 15,
    size: 68,
    bg: "bg-teal-500/20",
    text: "text-teal-100",
    delay: 0.6,
  },
  {
    label: "Micro-frontends",
    x: 75,
    y: 80,
    size: 66,
    bg: "bg-green-500/20",
    text: "text-green-100",
    delay: 0.7,
  },
  {
    label: "Performance",
    x: 88,
    y: 20,
    size: 64,
    bg: "bg-violet-500/20",
    text: "text-violet-100",
    delay: 0.5,
  },
  {
    label: "REST APIs",
    x: 25,
    y: 85,
    size: 62,
    bg: "bg-teal-400/20",
    text: "text-teal-100",
    delay: 0.4,
  },
  {
    label: "Axios",
    x: 60,
    y: 85,
    size: 58,
    bg: "bg-indigo-400/20",
    text: "text-indigo-100",
    delay: 0.5,
  },
  {
    label: "Docker",
    x: 80,
    y: 50,
    size: 70,
    bg: "bg-blue-300/20",
    text: "text-blue-100",
    delay: 0.6,
  },
  {
    label: "CI/CD",
    x: 35,
    y: 90,
    size: 64,
    bg: "bg-pink-500/20",
    text: "text-pink-100",
    delay: 0.8,
  },
  {
    label: "RTL",
    x: 15,
    y: 15,
    size: 62,
    bg: "bg-red-400/20",
    text: "text-red-100",
    delay: 0.6,
  },
  {
    label: "Vitest",
    x: 28,
    y: 10,
    size: 58,
    bg: "bg-rose-400/20",
    text: "text-rose-100",
    delay: 0.7,
  },
  {
    label: "GitHub",
    x: 90,
    y: 70,
    size: 60,
    bg: "bg-gray-500/20",
    text: "text-gray-100",
    delay: 0.4,
  },
  {
    label: "AI Tools",
    x: 12,
    y: 55,
    size: 62,
    bg: "bg-yellow-400/20",
    text: "text-yellow-100",
    delay: 0.9,
  },
];

export const experiences = [
  {
    id: 0,
    img: RealpageLogo,
    role: "Website Implementation Specialist II",
    company: "RealPage India Pvt Ltd",
    date: "May 2024 – Present",
    desc: "Designed and developed an internal Website Validation Tool to automate QA checks on live websites, improving quality and consistency.\n\nBuilt configurable validation features based on custom guidelines to detect content, accessibility, and UI issues across varying website structures.\n\nReduced manual validation effort and improved turnaround time by automating quality checks.\n\nDeveloped reusable frontend components and configurable features for CMS-driven applications, improving flexibility and maintainability.\n\nCollaborated with DevOps teams to deploy applications on GCP (GKE) using Docker and ensured production-ready builds.\n\nImproved UI performance by analyzing rendering behavior and reducing unnecessary re-renders.",
    skills: [
      "React.js",
      "TypeScript",
      "JavaScript",
      "Tailwind CSS",
      "Docker",
      "GCP (GKE)",
      "CI/CD",
      "Performance Optimization",
    ],
  },
  {
    id: 1,
    img: AspironLogo,
    role: "Software Associate & Technical Lead",
    company: "Aspiron Technologies",
    date: "Jan 2023 – Mar 2024",
    desc: "Led frontend development of a Campus Management ERP using React, Redux, and TypeScript, delivering scalable modules with reusable architecture.\n\nArchitected and implemented a micro-frontend architecture, enabling independent deployments and reducing release dependencies.\n\nMentored developers, conducted code reviews, and drove improvements in code quality and delivery consistency.\n\nBuilt a React Native mobile application with student and admin dashboards, improving accessibility and usability.\n\nImproved application performance using React Profiler, implementing code splitting, lazy loading, and render optimizations.\n\nDeveloped and maintained unit tests using Vitest and React Testing Library, minimizing regression issues.\n\nContainerized applications using Docker and integrated CI/CD pipelines for streamlined deployments.",
    skills: [
      "React.js",
      "Redux",
      "React Native",
      "TypeScript",
      "Micro-frontend Architecture",
      "Vitest",
      "React Testing Library",
      "Docker",
      "CI/CD",
      "Performance Optimization",
    ],
  },
  {
    id: 2,
    img: InflocurisLogo,
    role: "Senior Associate",
    company: "Inflocuris Consulting",
    date: "Feb 2020 – Nov 2021",
    desc: "Developed responsive web applications using HTML, CSS, and JavaScript for client and internal use.\n\nBuilt internal tools such as leave management and production tracking systems to improve operational efficiency.\n\nCollaborated with teams to fix UI issues, enhance usability, and improve overall application stability.",
    skills: ["HTML5", "CSS3", "JavaScript", "Bootstrap"],
  },
];

export const education = [
  {
    id: 0,
    school: "Nova's Institute of Technology, Eluru (JNTUK)",
    date: "2017 - 2020",
    grade: "6.89 CGPA",
    desc: "Bachelor of Technology in Mechanical Engineering. Developed strong analytical thinking and problem-solving skills, which later helped me transition into frontend development and build scalable web applications.",
    degree: "Bachelor of Technologyin Mechanical Engineering",
  },
  {
    id: 1,
    school: "Narayana Diploma & Engg. College, Tadipatri",
    date: "2013 - 2017",
    grade: "74%",
    desc: "Diploma in Mechanical Engineering. Built a solid foundation in logical reasoning, technical fundamentals, and hands-on problem-solving through practical coursework and projects.",
    degree: "Diploma in Mechanical Engineering",
  },
  {
    id: 2,
    school: "Board of Secondary Education, AP",
    date: "2012 - 2013",
    grade: "7.3 CGPA",
    desc: "Completed secondary education with a focus on core subjects, developing a strong academic foundation and disciplined learning approach.",
    degree: "Secondary School Certificate (SSC)",
  },
];
